name: Build IPA (iOS)

on:
  workflow_dispatch:

env:
  project_name: Byahe

jobs:
  build-debug-ipa:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      - name: Build project
        uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: iOS

      - name: Set up Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-version: '13.2'  # Adjust the Xcode version as needed

      - name: Build IPA using Xcode
        run: xcodebuild -workspace YourProject.xcworkspace -scheme YourScheme -configuration Release -archivePath build/YourProject.xcarchive archive
        working-directory: Build
        env:
          DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer  # Adjust the Xcode path as needed

      - name: Export IPA
        run: xcodebuild -exportArchive -archivePath build/YourProject.xcarchive -exportPath build -exportOptionsPlist ExportOptions.plist
        working-directory: Build

      - uses: actions/upload-artifact@v3
        with:
          name: IPA
          path: build/*.ipa
